set runtimepath+=/Users/bughunter/dotfiles/vim/addons/vam.vim
call vam#ActivateAddons(['Solarized', 'The_NERD_tree'])
" put this line first in ~/.vimrc
set nocompatible | filetype indent plugin on | syn on
syntax enable
set background=dark
colorscheme solarized


" NERDTree
autocmd vimenter * NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q
let NERDTreeMouseMode = 2
